-- Supabase SQL Editor에 붙여넣기
create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  draw_numbers integer[] not null,
  bonus_number integer not null,
  ticket_count integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists lotto_draws_created_at_idx
  on public.lotto_draws (created_at desc);

alter table public.lotto_draws enable row level security;

create policy if not exists "Allow anon insert"
  on public.lotto_draws
  for insert
  to anon
  with check (true);

create policy if not exists "Allow anon select"
  on public.lotto_draws
  for select
  to anon
  using (true);
